// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNwCBwcXLqNr3MotE5fk7P5YOA2elxoME',
    appId: '1:636968958613:web:3f7a80449f167aabfaf99c',
    messagingSenderId: '636968958613',
    projectId: 'sntr-mobile-banking-central',
    authDomain: 'sntr-mobile-banking-central.firebaseapp.com',
    storageBucket: 'sntr-mobile-banking-central.appspot.com',
    measurementId: 'G-E2HLRLM3ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSKiQZzz4_hWD4N7-htRFMbdWtwOQnvw',
    appId: '1:636968958613:android:6e2fcdef0a7a2f7cfaf99c',
    messagingSenderId: '636968958613',
    projectId: 'sntr-mobile-banking-central',
    storageBucket: 'sntr-mobile-banking-central.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoNXGbJrSmZk1-o_QerqevbGYZIIzkV9o',
    appId: '1:636968958613:ios:84670ff62b572f80faf99c',
    messagingSenderId: '636968958613',
    projectId: 'sntr-mobile-banking-central',
    storageBucket: 'sntr-mobile-banking-central.appspot.com',
    iosBundleId: 'com.sntrbankinglimited.sntrBankingManagementAgentEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoNXGbJrSmZk1-o_QerqevbGYZIIzkV9o',
    appId: '1:636968958613:ios:84670ff62b572f80faf99c',
    messagingSenderId: '636968958613',
    projectId: 'sntr-mobile-banking-central',
    storageBucket: 'sntr-mobile-banking-central.appspot.com',
    iosBundleId: 'com.sntrbankinglimited.sntrBankingManagementAgentEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNwCBwcXLqNr3MotE5fk7P5YOA2elxoME',
    appId: '1:636968958613:web:a5e9722a35d19e7ffaf99c',
    messagingSenderId: '636968958613',
    projectId: 'sntr-mobile-banking-central',
    authDomain: 'sntr-mobile-banking-central.firebaseapp.com',
    storageBucket: 'sntr-mobile-banking-central.appspot.com',
    measurementId: 'G-BDBPY17SXH',
  );
}
